# Configuration parameters
input_csv: "data/model_input.csv"
h5_path: "data/model_input.h5"
output_dir: "model_output"
embedding_dim: 1024
hidden_dim: 128
batch_size: 64
num_epochs: 500
learning_rate: 0.0001
early_stopping_patience: 5
