# pretrained.yaml
input_csv: "data/interm/training_data.csv"
h5_paths_glob: "data/protspace/training_data.h5"
tax_h5_path: "data/tax/binary_taxonomy_vectors.h5" # REQUIRED for Stage 1
output_dir: "model/model_output/pretrain_finetune_run"

# Strategy
training_strategy: "pretrain_finetune"

# Hyperparameters
use_focal_loss: false # CE
focal_loss_gamma: 2.0

batch_size: 64
hidden_dims: [256, 256]
dropout: 0.5

# Stage 2 Settings (Finetuning on Embeddings)
embedding_dim: 1024
num_epochs: 200
learning_rate: 0.0001
early_stopping_patience: 10
freeze_backbone: false   # Set 'true' to ONLY train the input mapping (stiffer model)

# Stage 1 Settings (Pretraining on Tax)
tax_dim: 56
tax_epochs: 50           # Tax learns fast, so 50 is usually enough
tax_lr: 0.001            # Higher LR for pretraining is common