"""Confidence-curation figure (reworked Fig 3 / new confidence panel).

PROVISIONAL: the confident-error verdict panel uses the frozen earlier-run
adjudication (n=63, pooled train/val/test) as a PLACEHOLDER. It will be replaced
by the re-curated set (test 81 + val 88 + 1/3 train = 232 confident errors at
calibrated confidence >= 0.8; blind sheet generated by
``scripts/build_confident_error_curation.py``) once expert curation completes.

Left panel  — held-out test set: calibrated-confidence rainclouds (half-violin +
              jittered points) for correct vs incorrect predictions; a zoom box marks
              the >= 0.8 error scatter that the right panel expands.
Right panel — the confident errors decomposed by curator verdict (vindicated /
              partial / false-positive), filled = held-out test, hollow = train/val.
"""
from __future__ import annotations

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.lines import Line2D
from matplotlib.patches import ConnectionPatch, FancyBboxPatch

from paper._paths import adjudication_csv
from paper.figures._common import (
    ADJUDICATION, DOUBLE_COL, apply_style, load_preds, save_fig,
)
from toxfam._paths import processed_dir

ADJ_CSV = adjudication_csv()

BLUE, AMBER, RED = ADJUDICATION["correct"], ADJUDICATION["partial"], ADJUDICATION["incorrect"]
GREY = "#BBBBBB"
COL = {"correct": BLUE, "partial": AMBER, "incorrect": RED}
MARK = {"correct": "o", "partial": "^", "incorrect": "s"}
ORDER = ["correct", "partial", "incorrect"]
VLABEL = {"correct": "vindicated", "partial": "partial", "incorrect": "false positive"}


def _load():
    d = load_preds("test_set", "nn_combined_run")
    correct = (d["actual_label"] == d["predicted_label"]).to_numpy()
    ca = d["confidence"].to_numpy()
    adj = pd.read_csv(ADJ_CSV)
    split = pd.read_csv(processed_dir() / "training_data.csv").set_index("identifier")["Split"]
    adj["is_test"] = adj["identifier"].map(split).eq("test").to_numpy()
    a = adj["assessment"].str.lower()
    verdict = {k: {"conf": adj.loc[a == k, "confidence"].to_numpy(),
                   "is_test": adj.loc[a == k, "is_test"].to_numpy()} for k in ORDER}
    n = {k: int((a == k).sum()) for k in ORDER}
    return ca[correct], ca[~correct], verdict, n


def _half_violin(ax, vals, base, color, width=0.42, bw=0.06):
    parts = ax.violinplot([vals], positions=[base], vert=True, widths=width * 2,
                          showextrema=False, bw_method=bw, side="low")
    for b in parts["bodies"]:
        v = b.get_paths()[0].vertices
        v[:, 1] = np.clip(v[:, 1], None, 1.0)
        b.set_facecolor(color)
        b.set_alpha(0.32)
        b.set_edgecolor(color)
        b.set_linewidth(0.6)


def _points_right(ax, vals, base, color, half=0.36, s=6, a=0.55, seed=0, sub=None):
    r = np.random.default_rng(seed)
    if sub and len(vals) > sub:
        vals = r.choice(vals, sub, replace=False)
    off = base + 0.06 + r.uniform(0, half, len(vals))
    ax.scatter(off, vals, s=s, color=color, alpha=a, edgecolor="none", rasterized=True, zorder=3)
    return float(off.min()), float(off.max())


def main() -> None:
    apply_style()
    cc, ci, V, N = _load()
    tot = sum(N.values())
    rng = np.random.default_rng(0)

    fig = plt.figure(figsize=(DOUBLE_COL, 3.5))
    axL = fig.add_axes([0.085, 0.16, 0.40, 0.72])
    axR = fig.add_axes([0.66, 0.16, 0.26, 0.72])

    # -- left: correct(left) + incorrect(right); violin-left, points-right --
    inc_xmin = inc_xmax = 1.0
    for i, (name, vals, col, ps, pa) in enumerate(
            [("correct", cc, BLUE, 2.0, 0.10), ("incorrect", ci, RED, 20, 0.6)]):
        _half_violin(axL, vals, i, col)
        xmin, xmax = _points_right(axL, vals, i, col, s=ps, a=pa, seed=i,
                                   sub=2500 if name == "correct" else None)
        if name == "incorrect":
            inc_xmin, inc_xmax = xmin, xmax
        axL.plot([i - 0.42, i + 0.02], [np.median(vals)] * 2, color=col, lw=1.2, zorder=5)
    axL.axhline(0.8, color=GREY, ls=(0, (4, 3)), lw=0.7, zorder=1)
    axL.set_xticks([0, 1])
    axL.set_xticklabels([f"correct\n($n$={len(cc):,})", f"incorrect\n($n$={len(ci)})"], fontsize=7)
    for t, c in zip(axL.get_xticklabels(), [BLUE, RED]):
        t.set_color(c)
    axL.set_xlim(-0.55, 1.6)
    axL.set_ylim(0.2, 1.02)
    axL.set_ylabel("Calibrated confidence")
    axL.set_title("Held-out test set", loc="left", fontsize=8.5, fontweight="bold")
    axL.tick_params(bottom=False)
    for s in ("top", "right"):
        axL.spines[s].set_visible(False)

    bx0, bx1, by0, by1 = inc_xmin - 0.03, inc_xmax + 0.05, 0.8, 1.005
    axL.add_patch(FancyBboxPatch((bx0, by0), bx1 - bx0, by1 - by0,
                                 boxstyle="round,pad=0.002,rounding_size=0.008",
                                 fill=False, edgecolor="0.35", lw=1.0, zorder=6))

    # -- right: confident errors zoomed; y-axis on right; filled/hollow split --
    for i, k in enumerate(ORDER):
        base = 2 - i
        x = V[k]["conf"]
        ist = V[k]["is_test"]
        col = COL[k]
        jit = base + rng.uniform(-0.30, 0.30, len(x))
        axR.scatter(jit[ist], x[ist], s=27, marker=MARK[k], facecolor=col, edgecolor="white",
                    linewidth=0.3, alpha=0.9, zorder=3)
        axR.scatter(jit[~ist], x[~ist], s=27, marker=MARK[k], facecolor="none", edgecolor=col,
                    linewidth=0.9, alpha=0.9, zorder=3)
        axR.plot([base - 0.34, base + 0.34], [x.mean()] * 2, color=col, lw=1.2, zorder=5)
    axR.set_xticks([2, 1, 0])
    axR.set_xticklabels([f"{VLABEL[k]}\n{N[k]}/{tot} ({N[k]/tot:.0%})" for k in ORDER], fontsize=7)
    for t, k in zip(axR.get_xticklabels(), ORDER):
        t.set_color(COL[k])
    axR.set_xlim(-0.55, 2.55)
    axR.set_ylim(0.8, 1.005)
    axR.yaxis.set_label_position("right")
    axR.yaxis.tick_right()
    axR.set_ylabel("Calibrated confidence  ($\\geq$0.8 zoom)")
    axR.set_title("Confident errors", loc="left", fontsize=8.5, fontweight="bold")
    axR.tick_params(bottom=False)
    axR.spines["top"].set_visible(False)
    axR.spines["left"].set_visible(False)
    axR.spines["right"].set_visible(True)
    axR.spines["right"].set_linewidth(0.6)
    axR.legend(
        handles=[Line2D([], [], marker="o", ls="none", mfc="0.3", mec="0.3", ms=5, label="test"),
                 Line2D([], [], marker="o", ls="none", mfc="none", mec="0.3", ms=5, label="train/val")],
        loc="lower right", fontsize=6, handletextpad=0.3, borderpad=0.3)

    for yb in (by0, by1):
        con = ConnectionPatch(xyA=(bx1, yb), coordsA=axL.transData, xyB=(-0.55, yb),
                              coordsB=axR.transData, color="0.55", lw=0.7, ls=(0, (3, 2)))
        con.set_in_layout(False)
        fig.add_artist(con)

    save_fig(fig, "figure_confidence_curation")


if __name__ == "__main__":
    main()
