"""Emit paper/figures/output/results_numbers.json — every cited number."""
from __future__ import annotations

import json
import warnings

import numpy as np
import pandas as pd
from rich.console import Console

from paper._paths import adjudication_csv, manuscript_tex_target, model_run_dir
from paper.figures._common import (
    FIG_DIR,
    LEN_BINS,
    MCC_CI_N_BOOT,
    load_preds,
    sequence_lengths,
    test_set_class_list,
)
from paper.stats import (
    accuracy_by_identity_bins,
    accuracy_by_length_bins,
    adjudication_summary,
    aligned_correctness,
    bootstrap_label_metric_ci,
    macro_mcc_by_support,
    mcnemar_test,
    micro_mcc,
    overall_mcc,
    paired_bootstrap_accuracy_diff,
    subset_accuracy,
    toxin_mask,
)
from toxfam._paths import benchmark_dir, get_project_root
from toxfam.evaluation.hbi import NO_HIT_LABEL
from toxfam.evaluation.metrics import is_nontoxin

ADJ_CSV = adjudication_csv()

console = Console()


def _boot_two_se(y_true, y_pred, metric_fn, *, n_boot: int = MCC_CI_N_BOOT, seed: int = 42) -> dict:
    """Point estimate of ``metric_fn`` plus +/-2 bootstrap standard errors.

    Thin wrapper over the shared :func:`bootstrap_label_metric_ci` (which backs the
    figures), pinned to 2000 resamples = the same convention as the binary
    external-tool comparison, and projected to the {point, two_se, n} shape the
    capability-matrix manifest emits. Delegating keeps the manifest's +/-2*SE in
    lockstep with the figures' instead of re-implementing the same bootstrap loop.
    """
    ci = bootstrap_label_metric_ci(y_true, y_pred, metric_fn, n_boot=n_boot, seed=seed)
    return {"point": ci["point"], "two_se": ci["two_se"], "n": ci["n"]}


def _emit_latex_macros(out: dict, path) -> None:
    r"""Write \newcommand macros for the headline statistics cited across the manuscript.

    results_numbers.json is the single source of truth; this LaTeX file is *derived*
    from it, formatted to the manuscript's display precision, so the figures, the
    manifest and the prose can never silently disagree. ``main()`` writes it both here
    (the committed code-repo artifact) and straight into the manuscript checkout, so the
    ``\input{results_numbers}`` copy can never drift from the generated one. Each macro
    expands to exactly the number the captions/body used to hard-code; macro names are
    letters-only (LaTeX forbids digits in \newcommand names).
    """
    mcc = out["mcc"]
    macros = {
        # overall (Gorodkin) multiclass MCC and the combined-model 95% CI
        "MccHbi": f"{mcc['hbi']['overall']:.3f}",
        "MccStandard": f"{mcc['nn_standard']['overall']:.3f}",
        "MccCombined": f"{mcc['nn_combined']['overall']:.3f}",
        "MccCombinedCIlow": f"{out['mcc_ci_nn_combined']['ci_low']:.3f}",
        "MccCombinedCIhigh": f"{out['mcc_ci_nn_combined']['ci_high']:.3f}",
        # micro-averaged MCC
        "MicroMccHbi": f"{mcc['hbi']['micro']:.3f}",
        "MicroMccStandard": f"{mcc['nn_standard']['micro']:.3f}",
        "MicroMccCombined": f"{mcc['nn_combined']['micro']:.3f}",
        # toxin-only accuracy (n = ToxNum test toxins)
        "ToxAccHbi": f"{out['toxin_only_acc']['hbi']:.3f}",
        "ToxAccStandard": f"{out['toxin_only_acc']['nn_standard']:.3f}",
        "ToxAccCombined": f"{out['toxin_only_acc']['nn_combined']:.3f}",
        # all-class accuracy (near-ceiling under the non-toxin prior)
        "AllAccHbi": f"{out['all_class_acc']['hbi']:.3f}",
        "AllAccStandard": f"{out['all_class_acc']['nn_standard']:.3f}",
        "AllAccCombined": f"{out['all_class_acc']['nn_combined']:.3f}",
        # cohort sizes and the non-toxin prior (percent)
        "NumTest": f"{out['n_test']:,}".replace(",", "{,}"),  # math-mode thousands sep
        "NumTox": str(out["toxin_only_n"]),
        "NontoxPrior": f"{out['non_toxin_prior'] * 100:.2f}",
    }
    header = [
        "% Auto-generated by paper/figures/numbers_manifest.py -- DO NOT EDIT BY HAND.",
        "% Single source of truth for the headline statistics cited in the manuscript,",
        "% derived from results_numbers.json. numbers_manifest.py writes this file straight",
        r"% into the manuscript repo too (when checked out), so \input{results_numbers} never drifts.",
        "",
    ]
    body = [f"\\newcommand{{\\{name}}}{{{val}}}" for name, val in macros.items()]
    path.write_text("\n".join(header + body) + "\n")


def main() -> None:
    classes = test_set_class_list()
    hbi = load_preds("test_set", "hbi")
    eat = load_preds("test_set", "eat")
    nn = load_preds("test_set", "nn_combined_run")
    std = load_preds("test_set", "nn_standard_run")
    nohit = hbi["predicted_label"] == NO_HIT_LABEL
    nn_nh = nn[nn["identifier"].isin(hbi.loc[nohit, "identifier"])]
    c_nn, c_hbi = aligned_correctness(nn, hbi)
    out = {
        "n_test": int(len(nn)),
        "non_toxin_prior": round(float((nn["actual_label"].str.lower() == "nontox").mean()), 4),
        "toxin_only_n": int(toxin_mask(nn).sum()),
        "toxin_only_acc": {"nn_combined": subset_accuracy(nn, toxin_mask(nn)),
                            "nn_standard": subset_accuracy(std, toxin_mask(std)),
                            "hbi": subset_accuracy(hbi, toxin_mask(hbi))},
        "all_class_acc": {"nn_combined": subset_accuracy(nn),
                          "nn_standard": subset_accuracy(std), "hbi": subset_accuracy(hbi)},
        "mcnemar": mcnemar_test(c_nn, c_hbi),
        "paired_bootstrap": paired_bootstrap_accuracy_diff(c_nn, c_hbi),
        "no_hit": {"n": int(nohit.sum()), "n_toxin": int(toxin_mask(nn_nh).sum()),
                   "nn_acc": subset_accuracy(nn_nh)},
        "mcc": {
            m: {"overall": overall_mcc(d["actual_label"], d["predicted_label"]),
                "micro": micro_mcc(d["actual_label"], d["predicted_label"], class_list=classes)}
            for m, d in [("hbi", hbi), ("nn_standard", std), ("nn_combined", nn)]
        },
        "mcc_ci_nn_combined": bootstrap_label_metric_ci(
            nn["actual_label"].values, nn["predicted_label"].values, overall_mcc, n_boot=MCC_CI_N_BOOT),
        # Family capability matrix (Table: binary + family). All-class accuracy and
        # overall MCC, each with +/-2 bootstrap SE, for the three family-capable methods
        # (the external toxin predictors are binary-only and absent here).
        "family_capability": {
            m: {
                "accuracy": _boot_two_se(
                    d["actual_label"].values, d["predicted_label"].values,
                    lambda a, b: float((a == b).mean())),
                "mcc": _boot_two_se(
                    d["actual_label"].values, d["predicted_label"].values, overall_mcc),
            }
            for m, d in [("hbi", hbi), ("eat", eat), ("nn_combined", nn)]
        },
        "macro_mcc_by_support": macro_mcc_by_support(nn, hbi, class_list=classes).to_dict("records"),
        "adjudication": adjudication_summary(ADJ_CSV),
    }

    # HBI binary toxic/non-toxic call: toxic iff the transferred family is a toxin
    # family ('no hit' and the non-toxin class -> non-toxic). HBI emits no score, so it
    # has no ROC-AUC/PR-AUC; only the discrete-call MCC is defined. Evaluated on the same
    # common subset (n=9,201) as the external-tool binary comparison so the MCC is
    # directly comparable to the score-based methods (read from the committed snapshot).
    scores_dir = get_project_root() / "scripts" / "external_tools" / "results" / "scores"
    common_ids = None
    for sm in ("toxfam_embtax", "eat", "toxinpred3", "toxdl2"):
        s = pd.read_csv(scores_dir / sm / "test_scores.csv")
        ids = set(s.loc[pd.to_numeric(s["score"], errors="coerce").notna(), "identifier"])
        common_ids = ids if common_ids is None else (common_ids & ids)
    hbi_c = hbi[hbi["identifier"].isin(common_ids)]
    cids = hbi_c["identifier"].tolist()
    y_true_bin = (~hbi_c["actual_label"].map(is_nontoxin)).to_numpy(dtype=int)
    y_pred_bin = (
        (~hbi_c["predicted_label"].map(is_nontoxin)) & (hbi_c["predicted_label"] != NO_HIT_LABEL)
    ).to_numpy(dtype=int)
    # Paired-bootstrap CI of the binary-MCC difference vs ToxFam (call = score >= 0.5),
    # same n / seed as the external-tool paired tests so the "tie" claim is backed.
    tox_call = (
        pd.read_csv(scores_dir / "toxfam_embtax" / "test_scores.csv")
        .drop_duplicates("identifier").set_index("identifier").loc[cids, "score"].to_numpy() >= 0.5
    ).astype(int)
    rng_hb = np.random.default_rng(42)
    diffs = np.empty(MCC_CI_N_BOOT, dtype=float)
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        for i in range(MCC_CI_N_BOOT):
            bi = rng_hb.integers(0, len(cids), size=len(cids))
            diffs[i] = overall_mcc(y_true_bin[bi], y_pred_bin[bi]) - overall_mcc(y_true_bin[bi], tox_call[bi])
    out["hbi_binary"] = {
        "n": int(len(hbi_c)),
        "subset": f"common_{len(hbi_c)}",
        "mcc": _boot_two_se(y_true_bin, y_pred_bin, overall_mcc),
        "paired_vs_toxfam_mcc": {
            "diff": float(diffs.mean()),
            "ci_low": float(np.percentile(diffs, 2.5)),
            "ci_high": float(np.percentile(diffs, 97.5)),
        },
        "note": "binary call = transferred-label class; no score, hence no ROC-AUC/PR-AUC",
    }

    # Toxin-only accuracy by sequence-length bin (M3: the <30 aa collapse, where HBI
    # degrades but the embedding model stays ~flat).
    lengths = sequence_lengths()

    def _len_block(d: pd.DataFrame) -> dict:
        b = accuracy_by_length_bins(d[toxin_mask(d)], lengths, bins=LEN_BINS)
        return {r["bin_label"]: {"accuracy": float(r["accuracy"]), "n": int(r["n"])}
                for _, r in b.iterrows()}

    out["length_bins_toxin_only"] = {
        "bins": LEN_BINS, "hbi": _len_block(hbi), "nn_combined": _len_block(nn),
    }

    # Toxin-only accuracy stratified by HBI best-hit sequence identity (the honest
    # "twilight-zone" view). HBI confidence == best-hit fractional identity; no-hit
    # queries (identity 0) are excluded. n_boot=2000 attaches a per-bin paired-bootstrap
    # CI of (ToxFam - HBI) so it is visible which strata are individually significant.
    # accuracy_by_identity_bins is the single source of truth for both the point estimates
    # and the CIs -- the binning is not re-derived here.
    id_bins = [0, 0.3, 0.4, 0.6, 0.8, 1.0001]
    id_labels = ["<0.3", "0.3-0.4", "0.4-0.6", "0.6-0.8", ">0.8"]
    id_tbl = accuracy_by_identity_bins(hbi, nn, bins=id_bins, labels=id_labels, n_boot=2000)
    out["identity_bins_toxin_only"] = {
        "bins": id_bins,
        "records": [
            {
                "bin": r["bin_label"], "n": int(r["n"]),
                "hbi_acc": float(r["hbi_accuracy"]), "toxfam_acc": float(r["other_accuracy"]),
                "diff": float(r["diff"]),
                "diff_ci_low": float(r["diff_ci_low"]), "diff_ci_high": float(r["diff_ci_high"]),
            }
            for _, r in id_tbl.iterrows()
        ],
    }

    # Binary toxic/non-toxic head metrics (gitignored artifact; include if present).
    binary = {}
    for model_name, run in (("nn_combined", "combined_run"), ("nn_standard", "standard_run")):
        bpath = model_run_dir(run) / "metrics" / "binary_metrics.json"
        if bpath.exists():
            bm = json.loads(bpath.read_text())
            td = bm.get("test_default", {})
            binary[model_name] = {
                "roc_auc": td.get("roc_auc"), "pr_auc": td.get("pr_auc"),
                "mcc": td.get("mcc"), "f1": td.get("f1"), "accuracy": td.get("accuracy"),
                "optimized_threshold": bm.get("optimized_threshold"),
            }
    if binary:
        out["binary_head"] = binary

    # Non-metazoan scope boundary — a NEGATIVE OOD result (ToxFam is metazoan-specific).
    # benchmark/ is gitignored; include only if the regenerated predictions are present.
    nm_path = benchmark_dir() / "non_metazoan" / "nn_combined_run" / "predictions.csv"
    if nm_path.exists():
        nm = pd.read_csv(nm_path)
        recognized = int(toxin_mask(nm, "predicted_label").sum())
        out["non_metazoan_scope_boundary"] = {
            "n": int(len(nm)),
            "recognized_as_toxic": recognized,
            "recognition_rate": round(recognized / len(nm), 4) if len(nm) else 0.0,
            "note": "all entries are non-metazoan toxins; low rate = ToxFam is metazoan-specific.",
        }

    FIG_DIR.mkdir(parents=True, exist_ok=True)
    (FIG_DIR / "results_numbers.json").write_text(json.dumps(out, indent=2, default=float))
    _emit_latex_macros(out, FIG_DIR / "results_numbers.tex")
    # Write the macros straight into the manuscript checkout too (when present) so the
    # \input{results_numbers} copy never drifts from the generated one. The figure PDFs
    # still need a manual copy because they require visual verification first; the numbers
    # do not, so syncing them automatically removes the cross-repo drift hazard.
    manuscript_tex = manuscript_tex_target()
    if manuscript_tex is not None:
        _emit_latex_macros(out, manuscript_tex)
        console.print(f"synced macros -> {manuscript_tex}")
    console.print_json(data=out, default=float)


if __name__ == "__main__":
    main()
