# 0_example_config.yaml

# 1. DATA
input_csv: "data/processed/training_data.csv"
h5_paths_glob: "data/processed/embeddings/training_data.h5"
tax_h5_path: "data/intermediate/taxonomy/binary_taxonomy_vectors.h5"
output_dir: "model/model_output/finetune"

# 2. STRATEGY (The Master Switch)
# Options: "standard" | "combined"
# standard is one MLP
# combined is a taxa and a tox MLP getting combined in the end
training_strategy: "standard"

# 3. HYPERPARAMETERS
use_focal_loss: true
focal_loss_gamma: 2.0
batch_size: 64
dropout: 0.5
hidden_dims: [256, 256]

# 4. STRATEGY-SPECIFIC SETTINGS
# Dimensions
embedding_dim: 1024
tax_dim: 56

# Training Settings
num_epochs: 200
learning_rate: 0.0001
early_stopping_patience: 10
