# standard.yaml
input_csv: "data/processed/training_data.csv"
h5_paths_glob: "data/processed/embeddings.h5"
# tax_h5_path is NOT needed for standard, but keeping it empty or defined prevents
# errors if your dataset class expects the key to exist (even if None).
tax_h5_path: null
output_dir: "model/model_output/standard_run"

# Strategy
training_strategy: "standard"

# Hyperparameters
batch_size: 64
hidden_dims: [256, 256]
dropout: 0.5
num_epochs: 200
learning_rate: 0.0001
early_stopping_patience: 10

# Dimensions (Only Embedding needed)
embedding_dim: 1024