"""Emit the Supplementary table of candidate ToxProt annotation gaps (Q3).

The gap set is the subset of I.K.'s blind curation where Swiss-Prot files a
protein as non-toxin but the curator judged it toxic, i.e. exactly the cases
where a confident ToxFam disagreement points at a missing annotation rather
than a model error. Confidence comes from the unblinded key, which the curation
file deliberately omits so the curation stayed blind.

Run:  uv run python -m paper.curation_table > /tmp/annotation_gaps.tex
"""

from __future__ import annotations

import sys

import pandas as pd

from paper._paths import curation_dir


def _escape(s: str) -> str:
    return (
        str(s)
        .replace("\\", r"\textbackslash ")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
        .replace("#", r"\#")
    )


def gap_set() -> pd.DataFrame:
    """The 146 Swiss-Prot-non-toxin / curator-toxin proteins, with confidence."""
    d = curation_dir()
    cur = pd.read_csv(d / "confident_errors_curated.tsv", sep="\t")
    key = pd.read_csv(d / "confident_errors_key.tsv", sep="\t")
    gaps = cur[(cur.swissprot_side == "nontoxin") & (cur.verdict == "tox")].copy()
    gaps = gaps.merge(key[["identifier", "confidence"]], on="identifier", how="left")
    if gaps.confidence.isna().any():
        raise SystemExit("confidence missing for some gap proteins; key file is stale")
    return gaps.sort_values(
        ["model_predicted_family", "confidence"], ascending=[True, False],
        ignore_index=True,
    )


def organism_names(taxids) -> dict[int, str]:
    import taxopy

    from toxfam.data.taxonomy import _resolve_taxdb_dir

    db = taxopy.TaxDb(taxdb_dir=str(_resolve_taxdb_dir()))
    out = {}
    for t in sorted({int(x) for x in taxids}):
        try:
            out[t] = taxopy.Taxon(t, db).name
        except Exception:
            out[t] = f"taxon {t}"
    return out


def main() -> None:
    gaps = gap_set()
    names = organism_names(gaps.organism_id)
    rows = []
    for r in gaps.itertuples():
        rows.append(
            " & ".join(
                [
                    _escape(r.identifier),
                    _escape(r.model_predicted_family),
                    f"\\emph{{{_escape(names[int(r.organism_id)])}}}",
                    f"{r.confidence:.3f}",
                    "partial" if r.assessment == "partial" else "yes",
                ]
            )
            + r" \\"
        )
    print(f"% {len(gaps)} candidate annotation gaps; generated by paper/curation_table.py")
    print("\n".join(rows))
    print(
        f"% families={gaps.model_predicted_family.nunique()} "
        f"correct={(gaps.assessment == 'correct').sum()} "
        f"partial={(gaps.assessment == 'partial').sum()}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
